# Generated by Django 3.2.4 on 2021-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20210713_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipt',
            name='items',
            field=models.ManyToManyField(null=True, to='items.Item'),
        ),
    ]
