# Generated by Django 3.2.4 on 2021-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_recipt_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='barCode',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
