# Generated by Django 3.2.4 on 2021-06-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210628_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('meats', 'meats'), ('bakery', 'bakery'), ('produce', 'produce'), ('dairy', 'dairy'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
